import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { ConfigProvider } from "antd";
import enUS from "antd/locale/en_US";
import zhCN from "antd/locale/zh_CN";

export type Locale = "zh-CN" | "en-US";

export const zh = {
  "app.title": "青玄 | 自动渗透agent",
  "language.switchToEnglish": "切换到英文",
  "language.switchToChinese": "切换到中文",
  "language.english": "English",
  "language.chinese": "中文",
  "common.load": "载入",
  "common.start": "启动",
  "common.stop": "停止",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.refresh": "刷新",
  "common.clear": "清除",
  "common.apply": "应用",
  "common.previous": "上一页",
  "common.next": "下一页",
  "common.none": "无",
  "common.unknown": "未知",
  "common.justNow": "刚刚",
  "common.minutesAgo": "{value} 分钟前",
  "common.hoursAgo": "{value} 小时前",
  "common.daysAgo": "{value} 天前",
  "common.active": "活跃",
  "common.idle": "空闲",
  "common.items": "{value} 项",
  "auth.brand": "青玄",
  "auth.tagline": "统一观察智能体的判断、行动与证据。",
  "auth.description": "面向安全研究与授权评测的多 Agent 运行工作台，集中管理实时轨迹、三图状态、任务队列和证据产物。",
  "auth.capability.trace": "实时轨迹",
  "auth.capability.traceDescription": "聚合 Agent 想法、动作和工具返回",
  "auth.capability.graph": "三图推理",
  "auth.capability.graphDescription": "推理图、作战图与任务树同步联动",
  "auth.capability.session": "会话管理",
  "auth.capability.sessionDescription": "快速切换历史 Runtime 与执行上下文",
  "auth.capability.protection": "访问保护",
  "auth.capability.protectionDescription": "账号会话隔离敏感运行数据",
  "auth.serviceReady": "认证服务就绪",
  "auth.sessionProtected": "会话已保护",
  "auth.sqlitePersistence": "SQLite 持久化",
  "auth.access": "工作台访问",
  "auth.enterWorkbench": "进入青玄工作台",
  "auth.accessDescription": "使用团队账号登录，或注册一个新的分析员账号。",
  "auth.login": "登录",
  "auth.register": "注册",
  "auth.securityNote": "密码仅以加盐哈希保存，会话使用 HttpOnly Cookie。",
  "auth.username": "用户名",
  "auth.password": "密码",
  "auth.displayName": "显示名称",
  "auth.confirmPassword": "确认密码",
  "auth.usernameRequired": "请输入用户名",
  "auth.passwordRequired": "请输入密码",
  "auth.displayNameRequired": "请输入显示名称",
  "auth.usernamePattern": "使用 3-32 位字母、数字或 ._-",
  "auth.passwordLength": "密码至少 8 位",
  "auth.confirmPasswordRequired": "请再次输入密码",
  "auth.passwordMismatch": "两次输入的密码不一致",
  "auth.passwordPlaceholder": "输入密码",
  "auth.displayNamePlaceholder": "安全分析员",
  "auth.passwordMinPlaceholder": "至少 8 位",
  "auth.confirmPasswordPlaceholder": "再次输入密码",
  "auth.loginWorkbench": "登录并继续",
  "auth.createAccount": "创建账号并进入",
  "nav.close": "关闭导航",
  "nav.open": "打开导航",
  "nav.trace": "实时轨迹",
  "nav.reports": "产物与报告",
  "nav.traffic": "Web Traffic",
  "nav.connections": "连接",
  "nav.skills": "Skills",
  "nav.mcp": "MCP",
  "nav.capabilities": "Capabilities",
  "nav.reasoning": "推理图",
  "nav.operation": "作战图",
  "nav.memory": "图记忆",
  "nav.task": "任务图",
  "nav.approvals": "危险操作批准",
  "nav.credentials": "凭证管理",
  "approvals.title": "待批准请求",
  "approvals.description": "模型请求执行危险操作前会在此等待人工批准，等待期间 Agent 保持挂起。",
  "approvals.empty": "当前没有待批准的危险操作",
  "credentials.description": "维护当前 Runtime 的内置凭据库：查看条目、查看明文、新增、标记失效与物理删除；所有操作都会写入审计日志。",
  "credentials.empty": "当前 Runtime 还没有凭据",
  "credentials.unavailable": "所选 Runtime 尚未初始化凭据存储，请先启动一次任务。",
  "credentials.loadFailed": "加载凭据失败",
  "credentials.reload": "重新加载",
  "credentials.refresh": "刷新",
  "credentials.total": "共 {value} 条",
  "credentials.search": "搜索标签 / 主机 / 用户名 / Scope",
  "credentials.filterKind": "类型筛选",
  "credentials.filterStatus": "状态筛选",
  "credentials.kindAll": "全部类型",
  "credentials.statusAll": "全部状态",
  "credentials.statusValid": "仅有效",
  "credentials.statusInvalid": "仅失效",
  "credentials.noMatches": "没有匹配的凭据",
  "credentials.columnKind": "类型",
  "credentials.columnLabel": "标签",
  "credentials.columnHost": "目标主机",
  "credentials.columnScope": "Scope",
  "credentials.columnRole": "角色",
  "credentials.columnSource": "来源",
  "credentials.columnValid": "状态",
  "credentials.columnCreated": "创建时间",
  "credentials.columnActions": "操作",
  "credentials.validTag": "有效",
  "credentials.invalidTag": "已失效",
  "credentials.create": "新增凭据",
  "credentials.createTitle": "新增凭据",
  "credentials.formKind": "类型",
  "credentials.formValue": "凭据值",
  "credentials.formValuePlaceholder": "粘贴 Cookie / Token / 密码等",
  "credentials.formValueRequired": "请输入凭据值",
  "credentials.formScope": "Scope（必填）",
  "credentials.formScopeHint": "通常为运行时 Run 引用，可复用现有值",
  "credentials.formScopeRequired": "请输入 Scope",
  "credentials.formHost": "目标主机",
  "credentials.formLabel": "标签",
  "credentials.formUsername": "用户名",
  "credentials.formRole": "角色",
  "credentials.formOptional": "可选",
  "credentials.submit": "创建",
  "credentials.cancel": "取消",
  "credentials.created": "凭据已创建",
  "credentials.invalidated": "凭据已标记失效",
  "credentials.deleted": "凭据已删除",
  "credentials.actionFailed": "操作失败",
  "credentials.reveal": "查看值",
  "credentials.invalidate": "标记失效",
  "credentials.delete": "删除",
  "credentials.revealTitle": "凭据明文",
  "credentials.revealHint": "查看明文将写入审计日志（操作者：当前 Web 账号）。",
  "credentials.copy": "复制",
  "credentials.copied": "已复制到剪贴板",
  "credentials.copyFailed": "复制失败，请手动选择复制",
  "credentials.invalidateConfirm": "确认将该凭据标记为失效？",
  "credentials.deleteConfirm": "删除后索引与密钥文件都会被移除且不可恢复，确认删除？",
  "credentials.validTotal": "有效 {value} 条",
  "credentials.invalidTotal": "失效 {value} 条",
  "credentials.lastUsed": "最近使用 {value}",
  "approvals.intent": "意图解析",
  "approvals.noIntent": "未提供意图解析",
  "approvals.tool": "工具调用",
  "approvals.args": "调用参数",
  "approvals.task": "所属任务",
  "approvals.scope": "授权范围",
  "approvals.riskLevel": "风险等级",
  "approvals.reason": "判定理由",
  "approvals.noReason": "未提供理由",
  "approvals.riskLow": "低",
  "approvals.riskMedium": "中",
  "approvals.riskHigh": "高",
  "approvals.approve": "批准执行",
  "approvals.deny": "拒绝",
  "approvals.waiting": "等待批准",
  "approvals.mode": "批准模式",
  "approvals.modeOff": "关闭（不拦截）",
  "approvals.modeAuto": "自动（只读放行 + LLM 风险评估）",
  "approvals.modeStrict": "严格（每次调用均需批准）",
  "approvals.pendingCount": "{value} 个待批准请求",
  "approvals.requireAdmin": "只有管理员可以批准或拒绝危险操作",
  "approvals.readOnly": "你的账号无权处理批准请求",
  "approvals.retry": "重试",
  "approvals.deciding": "处理中",
  "approvals.decideFailed": "操作失败：{error}",
  "approvals.switchMode": "批准模式",
  "approvals.switchSuccess": "批准模式已切换为 {mode}",
  "approvals.switchFailed": "切换批准模式失败：{error}",
  "approvals.confirmOffTitle": "关闭批准拦截？",
  "approvals.confirmOffDesc": "切换到 off 后，危险操作将不再需要人工批准，Agent 可自主执行全部工具调用。",
  "approvals.liveNotice": "切换即时生效：包括正在运行的 Agent 的下一次工具调用。",
  "app.approvalsStageTitle": "批准或拒绝 Agent 的危险操作请求",
  "app.approvalsStageSubtitle": "等待批准期间 Agent 保持挂起；批准后继续执行，拒绝则阻断该次调用。",
  "sidebar.sessions": "运行会话",
  "sidebar.noSessions": "暂无会话",
  "sidebar.standalone": "独立会话",
  "sidebar.agentStatus": "Agent 状态",
  "sidebar.noEvents": "暂无事件",
  "sidebar.noGoal": "暂无目标摘要",
  "sidebar.tasksTrace": "{tasks} 个任务 · {events} 条轨迹 · {time}",
  "sidebar.continue": "基于已有成果继续渗透",
  "agent.detailTitle": "Agent 详情",
  "agent.viewDetail": "查看详情",
  "agent.currentWork": "当前工作",
  "agent.recentActivity": "最近活动",
  "agent.noActivity": "该 Agent 暂无活动记录",
  "agent.noEventYet": "该 Agent 尚未产生事件",
  "agent.eventCount": "{value} 条事件",
  "agent.lastActive": "最近活动",
  "agent.activeNow": "活跃中",
  "agent.idle": "空闲",
  "agent.viewInTrace": "在运行轨迹中查看",
  "agent.decision": "决策",
  "agent.observation": "观察",
  "agent.command": "命令",
  "agent.desc.planner": "拆解目标、维护任务图并决定下一步规划",
  "agent.desc.executor": "执行任务步骤、调用工具并提交任务结果",
  "agent.desc.observer": "监督执行进展与证据并产出控制信号",
  "agent.desc.runtime": "管理运行生命周期、会话与流量基础设施",
  "app.connectionsInspectorTitle": "连接管理",
  "app.connectionsInspectorDescription": "管理员可控制托管的 SSH/chisel 连接。原始或非托管连接仅展示，不会自动关联到任务或会话。",
  "app.runtimeDirectory": "Runtime 目录",
  "app.startTask": "启动任务",
  "app.stopConfirm": "停止当前任务？",
  "app.stopDescription": "将优雅中断该运行，已产出的数据会保留。",
  "app.refreshRuntime": "刷新运行态",
  "app.autoRefresh": "自动刷新",
  "app.openInspector": "打开详情",
  "app.userMenu": "用户菜单",
  "app.administrator": "管理员",
  "app.analyst": "分析员",
  "app.logout": "退出登录",
  "app.currentGoal": "当前目标",
  "app.initializingGoal": "任务启动中…",
  "app.waitingRuntime": "等待运行态数据",
  "app.scopeFallback": "加载 Runtime 后展示目标、范围与当前执行状态。",
  "app.running": "运行中",
  "app.updatedAt": "更新于 {time}",
  "app.notLoaded": "尚未加载",
  "app.inspectorDrawer": "详情检查器",
  "app.traceTitle": "Agent 运行轨迹",
  "app.traceStageTitle": "Agent 正在判断什么、执行什么、观察到什么",
  "app.traceStageSubtitle": "选择任意事件，在右侧查看证据、Artifact、图引用与原始载荷。",
  "app.trafficStageTitle": "捕获、检查并安全 Replay HTTP 流量",
  "app.trafficStageSubtitle": "按 method、host、status 与执行引用过滤；body 仅在请求时加载。",
  "app.connectionsStageTitle": "连接、隧道与会话状态",
  "app.connectionsStageSubtitle": "管理员可控制托管 SSH/chisel 生命周期；分析员和非托管/原始连接保持只读。",
  "app.skillsStageTitle": "管理模型可用的项目 Skills",
  "app.skillsStageSubtitle": "查看 Registry 状态、诊断信息与模型调用权限；此页面不依赖当前 Runtime。",
  "app.mcpStageTitle": "管理模型可用的 MCP 服务器",
  "app.mcpStageSubtitle": "查看 MCP 服务器配置状态、可用工具与启用开关；此页面不依赖当前 Runtime。",
  "app.capabilitiesStageTitle": "管理 Skill、MCP 与专精 Agent",
  "app.capabilitiesStageSubtitle": "统一查看能力资源、启停开关与可配置选项；此页面不依赖当前 Runtime。",
  "capabilities.tabSkills": "Skill",
  "capabilities.tabMcp": "MCP",
  "capabilities.tabAgents": "专精 Agent",
  "app.credentialsStageTitle": "维护当前 Runtime 的内置凭据库",
  "app.credentialsStageSubtitle": "查看、新增、标记失效与物理删除 Credential MCP 存储；所有操作都会写入审计日志。",
  "skills.description": "检查项目 Skill，并控制是否允许模型在任务中选择。",
  "skills.search": "搜索名称或描述",
  "skills.filterLabel": "Skill 状态",
  "skills.filterAll": "全部状态",
  "skills.filterEnabled": "已启用",
  "skills.filterDisabled": "已停用",
  "skills.filterInvalid": "无效",
  "skills.total": "{value} 个 Skill",
  "skills.enabled": "{value} 个已启用",
  "skills.invalid": "{value} 个无效",
  "skills.diagnostics": "{value} 条诊断",
  "skills.empty": ".agents/skills 中没有可用 Skill",
  "skills.noMatches": "没有符合筛选条件的 Skill",
  "skills.valid": "有效",
  "skills.invalidState": "Skill 无效，无法启用",
  "skills.modelInvocable": "可调用",
  "skills.notInvocable": "不可调用",
  "skills.operatorRequired": "仅管理员可修改 Skill 状态",
  "skills.readOnly": "当前账号仅可查看 Skill。",
  "skills.retry": "重试",
  "skills.refresh": "刷新",
  "skills.registryDiagnostics": "{value} 条 Registry 诊断",
  "skills.inspectorTitle": "Skill 管理",
  "skills.inspectorDescription": "管理员可以启用或停用有效且允许模型调用的 Skill；分析员仅可查看 Registry 状态。",
  "skills.columnDescription": "描述",
  "skills.columnValidity": "有效性",
  "skills.columnModelInvocation": "模型调用",
  "skills.columnEnabled": "启用",
  "mcp.description": "检查内置 MCP 服务器，并控制是否在任务中启动并向 Executor 注入工具。",
  "mcp.search": "搜索名称或描述",
  "mcp.filterLabel": "MCP 状态",
  "mcp.filterAll": "全部状态",
  "mcp.filterEnabled": "已启用",
  "mcp.filterDisabled": "已停用",
  "mcp.filterUnconfigured": "未配置",
  "mcp.total": "{value} 个服务器",
  "mcp.enabled": "{value} 个已启用",
  "mcp.unconfigured": "{value} 个未配置",
  "mcp.diagnostics": "{value} 条诊断",
  "mcp.empty": "没有可用的 MCP 服务器",
  "mcp.noMatches": "没有符合筛选条件的 MCP 服务器",
  "mcp.configured": "已配置",
  "mcp.notConfigured": "未配置",
  "mcp.notConfiguredState": "服务器未配置，无法启用",
  "mcp.operatorRequired": "仅管理员可修改 MCP 状态",
  "mcp.readOnly": "当前账号仅可查看 MCP 服务器。",
  "mcp.retry": "重试",
  "mcp.refresh": "刷新",
  "mcp.registryDiagnostics": "{value} 条 Registry 诊断",
  "mcp.inspectorTitle": "MCP 管理",
  "mcp.inspectorDescription": "管理员可以启用或停用已配置的 MCP 服务器；分析员仅可查看 Registry 状态。停用后，下一次任务将不再启动该服务器及其工具。",
  "agents.panelTitle": "专精 Agent",
  "agents.panelDescription": "每个专精 Agent 拥有独立的提示词、模型档位、工具面、技能策略与预算；Planner 按任务选择拥有者。",
  "agents.search": "搜索 Agent 名称、用途或适用边界",
  "agents.filterLabel": "专精 Agent 状态",
  "agents.filterAll": "全部",
  "agents.filterEnabled": "已启用",
  "agents.filterDisabled": "已停用",
  "agents.filterInvalid": "无效",
  "agents.refresh": "刷新",
  "agents.retry": "重试",
  "agents.registryDiagnostics": "{value} 条注册诊断",
  "agents.empty": "未发现任何专精 Agent",
  "agents.noMatches": "没有匹配的专精 Agent",
  "agents.readOnly": "分析员只能查看专精 Agent 状态与配置。",
  "agents.total": "{value} 个 Agent",
  "agents.enabled": "{value} 个已启用",
  "agents.invalid": "{value} 个无效",
  "agents.diagnostics": "{value} 条诊断",
  "agents.columnAgent": "Agent",
  "agents.columnDescription": "用途与适用边界",
  "agents.columnSource": "来源",
  "agents.columnCapabilities": "能力面",
  "agents.columnBudget": "预算",
  "agents.columnEnabled": "启用",
  "agents.columnOptions": "选项",
  "agents.sourceBuiltin": "内置",
  "agents.sourceProject": "项目级",
  "agents.execModule": "含模块代码",
  "agents.execPrompt": "仅声明式",
  "agents.disabledGroups": "已裁剪工具组",
  "agents.allToolGroups": "全部工具组可用",
  "agents.toolGroups": "{value} 个工具组",
  "agents.skillMode": "Skill：{value}",
  "agents.budgetSummary": "{turns} 轮 / 上限 {ceiling} / 片 {slice}",
  "agents.budgetTooltip": "单 Epoch 时间份额 {share}%；并发上限 {concurrency}",
  "agents.unbounded": "不限",
  "agents.operatorRequired": "需要管理员权限",
  "agents.invalidState": "Agent 无效，无法启用",
  "agents.requiredState": "Runtime 必需，不能停用",
  "agents.noOptions": "该 Agent 没有可配置选项",
  "agents.optionsButton": "配置",
  "agents.optionsTitle": "专精 Agent 选项",
  "agents.optionsSave": "保存",
  "agents.optionsReset": "恢复默认",
  "agents.optionsEmpty": "该 Agent 未声明可配置选项。",
  "agents.optionsPartlyFixed": "部分参数由作者固定",
  "agents.optionAuthorFixed": "作者固定",
  "agents.optionAuthorDefault": "作者默认：{value}",
  "agents.optionBoundCeiling": "上限",
  "agents.optionPlannerNumberHint": "Planner 将在 [{minimum}, {maximum}] 内选择具体取值。",
  "agents.optionPlannerListHint": "Planner 将从允许集合（{value} 项）中选择具体取值。",
  "agents.optionsMode": "选项模式",
  "agents.optionsModePlanner": "Planner 指定",
  "agents.optionsModeUser": "用户指定",
  "agents.optionsModeHint": "Planner 指定：此处填写的数字为上限，具体取值由 Planner 在边界内决定；用户指定：此处填写的值直接生效。",
  "agents.optionsModeAuthorDefault": "作者默认：{value}",
  "agents.optionsModeOverridden": "已覆盖作者默认",
  "agents.optionsModeReset": "恢复作者默认",
  "agents.authorFixedTooltip": "工具组、技能策略与预算由作者声明固定，能力页不可修改。",
  "agents.inspectorTitle": "专精 Agent 与 Planner 选择",
  "agents.inspectorDescription": "Planner 在 create_tasks 时按 Agent 的用途与适用边界选择拥有者；未指定时使用通用 Executor。切换 Agent 需要完成或归档当前任务后再创建后继任务。",
  "mcp.columnDescription": "描述",
  "mcp.columnTools": "工具",
  "mcp.columnConfigured": "配置状态",
  "mcp.columnEnabled": "启用",
  "mcp.toolsCount": "{value} 个工具",
  "env.title": "环境配置（.env）",
  "env.open": "环境配置",
  "env.search": "搜索变量名",
  "env.noMatches": "没有匹配的变量",
  "env.entriesCount": "{value} 个变量",
  "env.unappliedInput": "有未应用的输入",
  "env.unsavedConfirm": "放弃未保存的环境变量修改？",
  "env.description": "管理服务读取的 .env 变量；保存后立即更新当前进程，并对之后启动的任务生效。密钥类变量仅显示掩码，不会回传明文。",
  "env.adminOnly": "仅管理员可查看和修改环境配置。",
  "env.loadFailed": "环境配置加载失败",
  "env.reload": "重新加载",
  "env.columnKey": "变量",
  "env.columnValue": "值",
  "env.columnState": "状态",
  "env.columnActions": "操作",
  "env.stateSaved": "已保存",
  "env.stateEdited": "待保存",
  "env.stateNew": "新增",
  "env.stateRemoved": "待删除",
  "env.emptyValue": "（空值）",
  "env.edit": "编辑",
  "env.remove": "删除",
  "env.restore": "撤销",
  "env.confirmEdit": "应用",
  "env.cancelEdit": "取消",
  "env.newEntry": "新增变量",
  "env.keyPlaceholder": "变量名，如 FOFA_API_KEY",
  "env.valuePlaceholder": "变量值",
  "env.editValuePlaceholder": "输入新值",
  "env.addEntry": "添加",
  "env.invalidKey": "变量名需以字母或下划线开头，仅含字母、数字、下划线",
  "env.emptyValueNotAllowed": "变量值不能为空",
  "env.noEntries": "还没有环境变量",
  "env.discard": "放弃更改",
  "env.saveChanges": "保存更改",
  "env.changesCount": "{value} 项更改",
  "env.saveSuccess": "已保存到 .env，并对之后启动的任务生效",
  "env.sensitiveHint": "密钥类变量的当前值不会显示；编辑时输入的新值将覆盖原值。",
  "app.initializingTitle": "任务已启动，正在初始化",
  "app.initializingDescription": "Planner 正在进行首次规划，通常需要 30~90 秒。",
  "app.initializingHint": "第一张 Planner 卡片出现后页面会自动切换；页面每 5 秒自动刷新，无需手动操作。若长时间无事件，请检查 LLM 服务是否可用。",
  "metric.trace": "轨迹",
  "metric.nodes": "节点",
  "metric.edges": "关系",
  "metric.artifacts": "产物",
  "graph.reasoningSubtitle": "追踪证据、假设、漏洞与利用之间的推导关系。",
  "graph.operationSubtitle": "梳理主机、服务、端点、参数与凭据组成的攻击面。",
  "graph.taskSubtitle": "查看范围、目标与任务的树状关系；里程碑和阻塞项收纳在所属任务中。",
  "graph.searchPlaceholder": "搜索节点名称、ID 或类型",
  "graph.nodeType": "节点类型",
  "graph.edgeType": "关系类型",
  "graph.zoomOut": "缩小",
  "graph.zoomIn": "放大",
  "graph.fit": "适配画布",
  "graph.relayout": "重新布局",
  "graph.clearSelection": "清除选择",
  "graph.nodeList": "图节点列表",
  "graph.nodes": "节点",
  "graph.noMatchingNodes": "没有匹配节点",
  "graph.noVisibleNodes": "当前筛选条件下没有可展示的节点",
  "graph.counts": "{nodes} 个节点 · {edges} 个{relations}",
  "memory.title": "图记忆",
  "memory.subtitle": "公开互联网搜集沉淀的长期记忆，供后续任务直接复用",
  "memory.empty": "这个运行还没有图记忆。信息搜集 Agent 完成一轮搜集后会写入这里。",
  "memory.emptyHint": "只有被认定为结论的实体才会进图，搜索过程本身不会。",
  "memory.total": "记忆节点",
  "memory.confidence": "置信度",
  "memory.sources": "来源",
  "memory.observed": "已观察",
  "memory.inferred": "推断",
  "memory.unconfirmed": "未确认",
  "memory.masked": "{value} 条已脱敏",
  "memory.leadsOnly": "{value} 条为 scope 外线索",
  "memory.leadsOnlyHint": "这些节点在授权范围之外，仅作为线索保留，不能被规划为行动目标。",
  "memory.table.entity": "实体",
  "memory.table.type": "类型",
  "memory.table.confidence": "置信度",
  "memory.table.provenance": "来源",
  "memory.table.flags": "标记",
  "memory.flagMasked": "已脱敏",
  "memory.flagLead": "scope 外线索",
  "memory.flagImported": "外部导入",
  "memory.filterType": "实体类型",
  "memory.filterConfidence": "置信度",
  "memory.showGraph": "图谱",
  "memory.showTable": "清单",
  "memory.noProvenance": "无来源记录",
  "graph.treeRelations": "树关系",
  "graph.relations": "关系",
  "graph.milestones": "{value} 个里程碑",
  "graph.blockers": "{value} 个阻塞项",
  "trace.all": "全部",
  "trace.newestFirst": "最新优先",
  "trace.chronological": "时间顺序",
  "trace.empty": "当前筛选条件下没有 Trace 事件",
  "trace.decision": "决策",
  "trace.observation": "观察",
  "trace.next": "下一步",
  "trace.eventChain": "事件链",
  "trace.noSummary": "当前步骤没有可展示的判断摘要。",
  "trace.action": "执行动作",
  "trace.noAction": "本步骤没有触发外部工具动作。",
  "trace.expandDetails": "展开执行细节",
  "trace.aggregatedEvent": "查看聚合事件",
  "trace.rawEvent": "查看原始事件",
  "trace.recordedIntent": "Agent 想法",
  "trace.structuredIntent": "判断依据",
  "trace.derivedIntent": "行动目的",
  "trace.toolFailed": "工具执行失败",
  "trace.noToolOutput": "暂无工具输出",
  "startRun.title": "启动新任务",
  "startRun.continueTitle": "基于已有成果继续渗透",
  "startRun.continueAction": "继续渗透",
  "startRun.continueHint": "将在该会话已有任务图、成果、凭据与工件的基础上重开 Root Goal 并开始新一轮规划；可修改目标与授权范围。",
  "startRun.taskType": "任务类型",
  "startRun.pentest": "渗透测试",
  "startRun.ctf": "CTF 题目",
  "startRun.taskTypeHint": "渗透测试使用 Markdown 评分标准和报告模板；CTF 完成后生成 WP。",
  "startRun.goal": "任务目标",
  "startRun.goalRequired": "请输入任务目标",
  "startRun.goalPlaceholder": "例如：对授权目标 http://10.0.x.x 进行安全测试，寻找并提交所有 flag",
  "startRun.scope": "授权范围",
  "startRun.scopeRequired": "请输入授权范围",
  "startRun.scopePlaceholder": "例如：10.0.0.0/24,baidu.com,*.example.com",
  "startRun.scopeFile": "授权范围文件",
  "startRun.scopePreview": "文件解析范围",
  "startRun.scopePreviewContent": "文件解析范围内容",
  "startRun.modifyScopePreview": "修改",
  "startRun.addScopePreview": "添加",
  "startRun.fileReadFailed": "无法读取授权范围文件",
  "startRun.attachments": "任务附件",
  "startRun.attachmentsHint": "可选。上传题目附件、抓包、厂商公告、配置或凭据导出等材料：文件会持久化为本次运行的 Artifact，由 Planner 在需要它的任务里交给 Executor 复原（单个文件上限 32 MiB，最多 12 个）。",
  "startRun.attachmentTooLarge": "单个附件不能超过 {max}",
  "startRun.attachmentTooMany": "一次运行最多携带 {max} 个附件",
  "startRun.maxMinutes": "最大运行时间（分钟）",
  "startRun.parallelTasks": "并行任务数",
  "startRun.plannerCycles": "Planner 连续无进展上限",
  "resize.navigation": "调整导航栏宽度",
  "resize.inspector": "调整详情栏宽度",
  "resize.title": "{label}，双击恢复默认宽度",
  "connections.description": "托管 SSH/Chisel Route 在活动和历史 Run 中均可重连；Session 与原始连接只读。",
  "connections.empty": "当前 Runtime 暂无连接",
  "connections.managed": "可控制",
  "connections.unmanaged": "只读",
  "connections.desired": "期望状态",
  "connections.available": "可用",
  "connections.unavailable": "不可用",
  "connections.heartbeat": "心跳",
  "connections.error": "错误",
  "connections.viewGraph": "在状态图中查看",
  "connections.graph": "状态图",
  "connections.reconnect": "重连",
  "connections.forget": "忘记 Route",
  "connections.forgetConfirm": "永久忘记这个 Route？",
  "status.live": "在线",
  "status.degraded": "异常",
  "status.stale": "过期",
  "status.closed": "已关闭",
  "status.running": "运行中",
  "status.stopped": "已停止",
  "status.completed": "已完成",
  "status.blocked": "已阻塞",
  "status.pending": "等待中",
  "status.failed": "失败",
  "inspector.currentStep": "当前步骤",
  "inspector.nodeDetails": "节点详情",
  "inspector.selectTrace": "选择一条 Trace 查看详情",
  "inspector.summarySource": "摘要来源",
  "inspector.publicOutput": "Agent 公开输出",
  "inspector.structuredReason": "结构化理由",
  "inspector.derivedPurpose": "系统派生目的",
  "inspector.action": "动作",
  "inspector.noExternalAction": "无外部动作",
  "inspector.stage": "阶段",
  "inspector.event": "事件",
  "inspector.task": "任务",
  "inspector.time": "时间",
  "inspector.commandDetails": "命令明细",
  "inspector.noArtifact": "无关联 Artifact",
  "inspector.aggregatedEvent": "聚合事件",
  "inspector.rawEvent": "原始事件",
  "inspector.loadingContent": "正在加载内容…",
  "inspector.loadContentFailed": "无法加载完整内容：{error}",
  "inspector.truncatedContent": "（内容过大，仅显示前段）",
  "inspector.selectNode": "选择图中的节点查看属性与关系",
  "inspector.milestones": "里程碑 {value}",
  "inspector.blockers": "阻塞项 {value}",
  "inspector.noMilestones": "暂无里程碑",
  "inspector.noBlockers": "暂无阻塞项",
  "inspector.evidence": "证据",
  "inspector.evidenceCount": "{value} 条证据",
  "inspector.noRefs": "无关联引用",
  "inspector.incoming": "入边 {value}",
  "inspector.outgoing": "出边 {value}",
  "inspector.noRelations": "无关系",
  "inspector.taskQueue": "任务队列 · {value}",
  "inspector.noTasks": "暂无任务",
  "traffic.filters": "Traffic 过滤器",
  "traffic.methodFilter": "Method 过滤",
  "traffic.hostFilter": "Host 过滤",
  "traffic.statusFilter": "Status 过滤",
  "traffic.taskRefFilter": "Task ref 过滤",
  "traffic.runRefFilter": "Run ref 过滤",
  "traffic.modeFilter": "Mode 过滤",
  "traffic.errorFilter": "Error 过滤",
  "traffic.onlyErrors": "仅错误",
  "traffic.noErrors": "无错误",
  "traffic.refresh": "刷新 Traffic",
  "traffic.empty": "没有匹配的流量记录",
  "traffic.pageSize": "每页最多 {value} 条",
  "traffic.selectExchange": "选择 exchange {value}",
  "traffic.unknownHost": "未知主机",
  "traffic.requestObserved": "请求 {captured} / {observed} 已观察",
  "traffic.responseObserved": "响应 {captured} / {observed} 已观察",
  "traffic.capturedObserved": "{captured} 已捕获 / {observed} 已观察",
  "traffic.inspector": "TRAFFIC 检查器",
  "traffic.exchangeDetails": "Exchange 详情",
  "traffic.selectRecord": "选择一条流量记录查看详情",
  "traffic.started": "开始",
  "traffic.completed": "完成",
  "traffic.duration": "耗时",
  "traffic.protocol": "协议",
  "traffic.mode": "模式",
  "traffic.requestBytes": "请求字节",
  "traffic.responseBytes": "响应字节",
  "traffic.error": "错误",
  "traffic.requestHeaders": "请求 Headers",
  "traffic.responseHeaders": "响应 Headers",
  "traffic.requestBody": "请求 Body",
  "traffic.responseBody": "响应 Body",
  "traffic.headersTruncated": "Headers 已截断{reason}",
  "traffic.noHeaders": "未记录 headers",
  "traffic.displayFormat": "{side} 展示格式",
  "traffic.loadingOnDemand": "正在按需加载…",
  "traffic.bodyReadFailed": "Body 无法读取，可能已淘汰或过大：{error}",
  "traffic.loadBody": "加载 body（最大 256 KiB）",
  "traffic.bodyTruncated": "Body 仅显示已捕获部分（截断{reason}）",
  "traffic.replayAdminOnly": "仅管理员可发送 Replay；分析员可查看原始 exchange。",
  "traffic.editReplay": "编辑并 Replay",
  "traffic.replayMethod": "Replay Method",
  "traffic.replayUrl": "Replay URL",
  "traffic.replayHeaderName": "Replay Header 名称 {value}",
  "traffic.replayHeaderValue": "Replay Header 值 {value}",
  "traffic.replayBody": "Replay Body",
  "traffic.deleteHeader": "删除 header {value}",
  "traffic.addHeader": "添加 header",
  "traffic.editedBody": "将发送编辑后的 body",
  "traffic.sourceBody": "Body 未修改，将由 sidecar 使用完整源 body",
  "traffic.prepareSend": "准备发送",
  "traffic.confirmReplay": "确认发送 Replay",
  "traffic.confirmSend": "确认发送",
  "traffic.replayWarning": "Replay 可能携带敏感 header 与 body",
  "traffic.replayWarningDescription": "请确认你有权向目标发送该请求。敏感值不会写入 URL、localStorage 或前端日志。",
  "traffic.headersCount": "{value} 项（可能含 Authorization/Cookie）",
  "traffic.bodyOverride": "{value} 字符（{mode} override）",
  "traffic.fullSourceBody": "使用完整源 body（无 override）",
  "traffic.referenceChain": "关联链",
  "traffic.noReferenceChain": "无 task/run/route/session/connect 关联",
  "traffic.bodyAvailable": "Body 尚未加载；点击后按需读取，最大 256 KiB。",
  "traffic.bodyEvicted": "Body 已从捕获存储淘汰。",
  "traffic.bodyUnavailableTruncated": "Body 过大或已截断，且没有可读取引用{reason}。",
  "traffic.bodyNoBytes": "Body 未捕获：该方向没有观察到 body 字节。",
  "traffic.bodyNotCaptured": "Body 未捕获（capture state: {state}）。",
  "traffic.invalidUrl": "无效 URL",
  "traffic.tcpReplayUnavailable": "TCP 流量仅支持检查，不能作为 HTTP Replay",
  "api.csrfUnavailable": "无法获取 CSRF token",
  "dashboard.sessionsFailed": "会话列表加载失败：{error}",
  "dashboard.runtimeFailed": "运行态加载失败：{error}"
} as const;

export const en = {
  "app.title": "青玄 | Autonomous Pentest Agent",
  "language.switchToEnglish": "Switch to English",
  "language.switchToChinese": "Switch to Chinese",
  "language.english": "English",
  "language.chinese": "中文",
  "common.load": "Load",
  "common.start": "Start",
  "common.stop": "Stop",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "common.apply": "Apply",
  "common.previous": "Previous",
  "common.next": "Next",
  "common.none": "None",
  "common.unknown": "Unknown",
  "common.justNow": "just now",
  "common.minutesAgo": "{value} min ago",
  "common.hoursAgo": "{value} hr ago",
  "common.daysAgo": "{value} days ago",
  "common.active": "active",
  "common.idle": "idle",
  "common.items": "{value} items",
  "auth.brand": "青玄",
  "auth.tagline": "Observe agent reasoning, actions, and evidence in one place.",
  "auth.description": "A multi-agent operations workbench for security research and authorized assessment, bringing live traces, tri-graph state, task queues, and evidence artifacts together.",
  "auth.capability.trace": "Live Trace",
  "auth.capability.traceDescription": "Aggregate agent thoughts, actions, and tool results",
  "auth.capability.graph": "Tri-Graph Reasoning",
  "auth.capability.graphDescription": "Keep reasoning, operation, and task graphs synchronized",
  "auth.capability.session": "Session Management",
  "auth.capability.sessionDescription": "Switch quickly between runtime history and execution contexts",
  "auth.capability.protection": "Access Protection",
  "auth.capability.protectionDescription": "Protect sensitive runtime data with account sessions",
  "auth.serviceReady": "Auth service ready",
  "auth.sessionProtected": "Session protected",
  "auth.sqlitePersistence": "SQLite persistence",
  "auth.access": "WORKSPACE ACCESS",
  "auth.enterWorkbench": "Enter Qingxuan Workbench",
  "auth.accessDescription": "Sign in with a team account or register a new analyst account.",
  "auth.login": "Sign in",
  "auth.register": "Register",
  "auth.securityNote": "Passwords are stored only as salted hashes; sessions use HttpOnly cookies.",
  "auth.username": "Username",
  "auth.password": "Password",
  "auth.displayName": "Display name",
  "auth.confirmPassword": "Confirm password",
  "auth.usernameRequired": "Enter your username",
  "auth.passwordRequired": "Enter your password",
  "auth.displayNameRequired": "Enter a display name",
  "auth.usernamePattern": "Use 3–32 letters, numbers, or ._-",
  "auth.passwordLength": "Password must be at least 8 characters",
  "auth.confirmPasswordRequired": "Enter the password again",
  "auth.passwordMismatch": "The passwords do not match",
  "auth.passwordPlaceholder": "Enter password",
  "auth.displayNamePlaceholder": "Security analyst",
  "auth.passwordMinPlaceholder": "At least 8 characters",
  "auth.confirmPasswordPlaceholder": "Enter password again",
  "auth.loginWorkbench": "Sign in and continue",
  "auth.createAccount": "Create account and continue",
  "nav.close": "Close navigation",
  "nav.open": "Open navigation",
  "nav.trace": "Live Trace",
  "nav.reports": "Artifacts & Reports",
  "nav.traffic": "Web Traffic",
  "nav.connections": "Connections",
  "nav.skills": "Skills",
  "nav.mcp": "MCP",
  "nav.capabilities": "能力",
  "nav.reasoning": "Reasoning Graph",
  "nav.operation": "Operation Graph",
  "nav.memory": "Graph Memory",
  "nav.task": "Task Graph",
  "nav.approvals": "Dangerous Actions",
  "nav.credentials": "Credentials",
  "approvals.title": "Pending approvals",
  "approvals.description": "Dangerous tool calls wait here for manual approval; the agent stays suspended meanwhile.",
  "approvals.empty": "No pending dangerous actions",
  "credentials.description": "Maintain the built-in credential store of the selected Runtime: inspect entries, reveal values, add, invalidate, or physically delete. Every action is written to the audit log.",
  "credentials.empty": "No credentials in this Runtime yet",
  "credentials.unavailable": "This Runtime has no credential store yet. Start a run first.",
  "credentials.loadFailed": "Failed to load credentials",
  "credentials.reload": "Reload",
  "credentials.refresh": "Refresh",
  "credentials.total": "{value} credentials",
  "credentials.search": "Search label / host / username / scope",
  "credentials.filterKind": "Kind filter",
  "credentials.filterStatus": "Status filter",
  "credentials.kindAll": "All kinds",
  "credentials.statusAll": "All statuses",
  "credentials.statusValid": "Valid only",
  "credentials.statusInvalid": "Invalid only",
  "credentials.noMatches": "No matching credentials",
  "credentials.columnKind": "Kind",
  "credentials.columnLabel": "Label",
  "credentials.columnHost": "Host",
  "credentials.columnScope": "Scope",
  "credentials.columnRole": "Role",
  "credentials.columnSource": "Source",
  "credentials.columnValid": "Status",
  "credentials.columnCreated": "Created",
  "credentials.columnActions": "Actions",
  "credentials.validTag": "Valid",
  "credentials.invalidTag": "Invalid",
  "credentials.create": "Add credential",
  "credentials.createTitle": "Add credential",
  "credentials.formKind": "Kind",
  "credentials.formValue": "Value",
  "credentials.formValuePlaceholder": "Paste a cookie / token / password",
  "credentials.formValueRequired": "Credential value is required",
  "credentials.formScope": "Scope (required)",
  "credentials.formScopeHint": "Usually the runtime runRef; reuse an existing value",
  "credentials.formScopeRequired": "A scope reference is required",
  "credentials.formHost": "Host",
  "credentials.formLabel": "Label",
  "credentials.formUsername": "Username",
  "credentials.formRole": "Role",
  "credentials.formOptional": "Optional",
  "credentials.submit": "Create",
  "credentials.cancel": "Cancel",
  "credentials.created": "Credential created",
  "credentials.invalidated": "Credential marked invalid",
  "credentials.deleted": "Credential deleted",
  "credentials.actionFailed": "Action failed",
  "credentials.reveal": "Reveal",
  "credentials.invalidate": "Invalidate",
  "credentials.delete": "Delete",
  "credentials.revealTitle": "Credential value",
  "credentials.revealHint": "Revealing the value is recorded in the audit log (actor: current web account).",
  "credentials.copy": "Copy",
  "credentials.copied": "Copied to clipboard",
  "credentials.copyFailed": "Copy failed; select and copy manually",
  "credentials.invalidateConfirm": "Mark this credential as invalid?",
  "credentials.deleteConfirm": "Deleting removes both the index entry and the secret file with no recovery. Delete?",
  "credentials.validTotal": "Valid {value}",
  "credentials.invalidTotal": "Invalid {value}",
  "credentials.lastUsed": "Last used {value}",
  "approvals.intent": "Intent",
  "approvals.noIntent": "No intent analysis",
  "approvals.tool": "Tool call",
  "approvals.args": "Arguments",
  "approvals.task": "Task",
  "approvals.scope": "Authorized scope",
  "approvals.riskLevel": "Risk level",
  "approvals.reason": "Rationale",
  "approvals.noReason": "No rationale",
  "approvals.riskLow": "Low",
  "approvals.riskMedium": "Medium",
  "approvals.riskHigh": "High",
  "approvals.approve": "Approve",
  "approvals.deny": "Deny",
  "approvals.waiting": "Awaiting approval",
  "approvals.mode": "Approval mode",
  "approvals.modeOff": "Off (no interception)",
  "approvals.modeAuto": "Auto (read-only pass + LLM risk assessment)",
  "approvals.modeStrict": "Strict (every call requires approval)",
  "approvals.pendingCount": "{value} pending approval requests",
  "approvals.requireAdmin": "Only administrators can approve or deny dangerous actions",
  "approvals.readOnly": "Your account cannot decide approval requests",
  "approvals.retry": "Retry",
  "approvals.deciding": "Processing",
  "approvals.decideFailed": "Decision failed: {error}",
  "approvals.switchMode": "Approval mode",
  "approvals.switchSuccess": "Approval mode switched to {mode}",
  "approvals.switchFailed": "Failed to switch approval mode: {error}",
  "approvals.confirmOffTitle": "Turn off approval interception?",
  "approvals.confirmOffDesc": "With mode off, dangerous actions no longer require human approval and the agent may run every tool call autonomously.",
  "approvals.liveNotice": "The switch takes effect immediately, including the next tool call of already running agents.",
  "app.approvalsStageTitle": "Approve or deny dangerous tool calls from the agent",
  "app.approvalsStageSubtitle": "The agent stays suspended while awaiting approval; approving resumes execution, denying blocks the call.",
  "sidebar.sessions": "Runtime Sessions",
  "sidebar.noSessions": "No sessions",
  "sidebar.standalone": "Standalone Sessions",
  "sidebar.agentStatus": "Agent Status",
  "sidebar.noEvents": "No events",
  "sidebar.noGoal": "No goal summary",
  "sidebar.tasksTrace": "{tasks} tasks · {events} traces · {time}",
  "sidebar.continue": "Continue from existing results",
  "agent.detailTitle": "Agent Details",
  "agent.viewDetail": "View details",
  "agent.currentWork": "Current work",
  "agent.recentActivity": "Recent activity",
  "agent.noActivity": "No activity recorded for this agent",
  "agent.noEventYet": "This agent has not produced any events yet",
  "agent.eventCount": "{value} events",
  "agent.lastActive": "Last active",
  "agent.activeNow": "Active now",
  "agent.idle": "Idle",
  "agent.viewInTrace": "View in live trace",
  "agent.decision": "Decision",
  "agent.observation": "Observation",
  "agent.command": "Command",
  "agent.desc.planner": "Decomposes goals, maintains the task graph, and decides the next plan",
  "agent.desc.executor": "Executes task steps, invokes tools, and submits task results",
  "agent.desc.observer": "Supervises progress and evidence, and produces control signals",
  "agent.desc.runtime": "Manages the run lifecycle, sessions, and traffic infrastructure",
  "app.connectionsInspectorTitle": "Connection Management",
  "app.connectionsInspectorDescription": "Administrators can control managed SSH/chisel connections. Raw and unmanaged connections are display-only and are not linked automatically to tasks or sessions.",
  "app.runtimeDirectory": "Runtime directory",
  "app.startTask": "Start run",
  "app.stopConfirm": "Stop the current run?",
  "app.stopDescription": "The run will be interrupted gracefully and existing data will be retained.",
  "app.refreshRuntime": "Refresh runtime",
  "app.autoRefresh": "Auto refresh",
  "app.openInspector": "Open inspector",
  "app.userMenu": "User menu",
  "app.administrator": "Administrator",
  "app.analyst": "Analyst",
  "app.logout": "Sign out",
  "app.currentGoal": "Current Goal",
  "app.initializingGoal": "Run starting…",
  "app.waitingRuntime": "Waiting for runtime data",
  "app.scopeFallback": "Load a runtime to view its goal, scope, and current execution status.",
  "app.running": "Running",
  "app.updatedAt": "Updated {time}",
  "app.notLoaded": "Not loaded",
  "app.inspectorDrawer": "Inspector",
  "app.traceTitle": "Agent Trace",
  "app.traceStageTitle": "What the agents are reasoning about, doing, and observing",
  "app.traceStageSubtitle": "Select an event to inspect evidence, artifacts, graph references, and the raw payload.",
  "app.trafficStageTitle": "Capture, inspect, and safely replay HTTP traffic",
  "app.trafficStageSubtitle": "Filter by method, host, status, and execution references; bodies load only on demand.",
  "app.connectionsStageTitle": "Connections, tunnels, and session status",
  "app.connectionsStageSubtitle": "Administrators control managed SSH/chisel lifecycles; analysts and unmanaged/raw connections remain read-only.",
  "app.skillsStageTitle": "Manage project Skills available to the model",
  "app.skillsStageSubtitle": "Review registry state, diagnostics, and model invocation access independently of the current runtime.",
  "app.mcpStageTitle": "Manage MCP servers available to the agent",
  "app.mcpStageSubtitle": "Review MCP server configuration, exposed tools, and enable switches independently of the current runtime.",
  "app.capabilitiesStageTitle": "Manage Skills, MCP servers and Specialist Agents",
  "app.capabilitiesStageSubtitle": "Review capability resources, enable switches and configurable options independently of the current runtime.",
  "capabilities.tabSkills": "Skills",
  "capabilities.tabMcp": "MCP",
  "capabilities.tabAgents": "Specialist Agents",
  "app.credentialsStageTitle": "Maintain the built-in credential store of the current runtime",
  "app.credentialsStageSubtitle": "List, create, invalidate, and physically delete entries of the built-in Credential MCP store; every action is written to the audit log.",
  "skills.description": "Inspect project Skills and control whether the model may select them during a task.",
  "skills.search": "Search by name or description",
  "skills.filterLabel": "Skill status",
  "skills.filterAll": "All statuses",
  "skills.filterEnabled": "Enabled",
  "skills.filterDisabled": "Disabled",
  "skills.filterInvalid": "Invalid",
  "skills.total": "{value} Skills",
  "skills.enabled": "{value} enabled",
  "skills.invalid": "{value} invalid",
  "skills.diagnostics": "{value} diagnostics",
  "skills.empty": "No usable Skills found in .agents/skills",
  "skills.noMatches": "No Skills match the current filters",
  "skills.valid": "Valid",
  "skills.invalidState": "This Skill is invalid and cannot be enabled",
  "skills.modelInvocable": "Invocable",
  "skills.notInvocable": "Not invocable",
  "skills.operatorRequired": "Only administrators can change Skill state",
  "skills.readOnly": "Your account has read-only access to Skills.",
  "skills.retry": "Retry",
  "skills.refresh": "Refresh",
  "skills.registryDiagnostics": "{value} registry diagnostics",
  "skills.inspectorTitle": "Skill management",
  "skills.inspectorDescription": "Administrators can enable or disable valid, model-invocable Skills. Analysts can inspect registry state only.",
  "skills.columnDescription": "Description",
  "skills.columnValidity": "Validity",
  "skills.columnModelInvocation": "Model invocation",
  "skills.columnEnabled": "Enabled",
  "mcp.description": "Inspect built-in MCP servers and control whether they start and inject tools into task executors.",
  "mcp.search": "Search by name or description",
  "mcp.filterLabel": "MCP status",
  "mcp.filterAll": "All statuses",
  "mcp.filterEnabled": "Enabled",
  "mcp.filterDisabled": "Disabled",
  "mcp.filterUnconfigured": "Unconfigured",
  "mcp.total": "{value} servers",
  "mcp.enabled": "{value} enabled",
  "mcp.unconfigured": "{value} unconfigured",
  "mcp.diagnostics": "{value} diagnostics",
  "mcp.empty": "No MCP servers available",
  "mcp.noMatches": "No MCP servers match the current filters",
  "mcp.configured": "Configured",
  "mcp.notConfigured": "Unconfigured",
  "mcp.notConfiguredState": "This server is not configured and cannot be enabled",
  "mcp.operatorRequired": "Only administrators can change MCP state",
  "mcp.readOnly": "Your account has read-only access to MCP servers.",
  "mcp.retry": "Retry",
  "mcp.refresh": "Refresh",
  "mcp.registryDiagnostics": "{value} registry diagnostics",
  "mcp.inspectorTitle": "MCP management",
  "mcp.inspectorDescription": "Administrators can enable or disable configured MCP servers; analysts can inspect registry state only. Disabling a server takes effect on the next run.",
  "agents.panelTitle": "Specialist Agents",
  "agents.panelDescription": "Each Specialist owns its prompt, model profile, tool surface, Skill policy and budget; the Planner picks the owner per Task.",
  "agents.search": "Search Agent name, purpose or scope",
  "agents.filterLabel": "Specialist status",
  "agents.filterAll": "All",
  "agents.filterEnabled": "Enabled",
  "agents.filterDisabled": "Disabled",
  "agents.filterInvalid": "Invalid",
  "agents.refresh": "Refresh",
  "agents.retry": "Retry",
  "agents.registryDiagnostics": "{value} registry diagnostic(s)",
  "agents.empty": "No Specialist Agent found",
  "agents.noMatches": "No matching Specialist Agent",
  "agents.readOnly": "Analysts can inspect Specialist status and options only.",
  "agents.total": "{value} Agent(s)",
  "agents.enabled": "{value} enabled",
  "agents.invalid": "{value} invalid",
  "agents.diagnostics": "{value} diagnostic(s)",
  "agents.columnAgent": "Agent",
  "agents.columnDescription": "Purpose and boundaries",
  "agents.columnSource": "Source",
  "agents.columnCapabilities": "Capabilities",
  "agents.columnBudget": "Budget",
  "agents.columnEnabled": "Enabled",
  "agents.columnOptions": "Options",
  "agents.sourceBuiltin": "Built-in",
  "agents.sourceProject": "Project",
  "agents.execModule": "Ships module code",
  "agents.execPrompt": "Declarative only",
  "agents.disabledGroups": "Removed tool groups",
  "agents.allToolGroups": "All tool groups available",
  "agents.toolGroups": "{value} tool group(s)",
  "agents.skillMode": "Skills: {value}",
  "agents.budgetSummary": "{turns} turns / cap {ceiling} / slice {slice}",
  "agents.budgetTooltip": "Epoch time share {share}%; concurrency cap {concurrency}",
  "agents.unbounded": "unbounded",
  "agents.operatorRequired": "Administrator permission required",
  "agents.invalidState": "Agent is invalid and cannot be enabled",
  "agents.requiredState": "Required by the runtime and cannot be disabled",
  "agents.noOptions": "This Agent declares no configurable options",
  "agents.optionsButton": "Configure",
  "agents.optionsTitle": "Specialist options",
  "agents.optionsSave": "Save",
  "agents.optionsReset": "Restore defaults",
  "agents.optionsEmpty": "This Agent declares no configurable options.",
  "agents.optionsPartlyFixed": "Some parameters are fixed by the author",
  "agents.optionAuthorFixed": "Fixed by author",
  "agents.optionAuthorDefault": "Author default: {value}",
  "agents.optionBoundCeiling": "Ceiling",
  "agents.optionPlannerNumberHint": "The Planner picks the concrete value within [{minimum}, {maximum}].",
  "agents.optionPlannerListHint": "The Planner picks the concrete value from the allowed set ({value} entries).",
  "agents.optionsMode": "Options mode",
  "agents.optionsModePlanner": "Planner decides",
  "agents.optionsModeUser": "Operator decides",
  "agents.optionsModeHint": "Planner decides: the number entered here is an upper bound and the Planner picks the concrete value inside it; Operator decides: the value entered here takes effect directly.",
  "agents.optionsModeAuthorDefault": "Author default: {value}",
  "agents.optionsModeOverridden": "Overrides the author default",
  "agents.optionsModeReset": "Reset to author default",
  "agents.authorFixedTooltip": "Tool groups, Skill policy and budget are fixed by the author's declaration and cannot be changed on this page.",
  "agents.inspectorTitle": "Specialist Agents and Planner selection",
  "agents.inspectorDescription": "The Planner picks a Task owner from each Agent's purpose and boundaries during create_tasks; omitting the field uses the general Executor. Switching owners requires completing or archiving the current Task and creating a successor.",
  "mcp.columnDescription": "Description",
  "mcp.columnTools": "Tools",
  "mcp.columnConfigured": "Configuration",
  "mcp.columnEnabled": "Enabled",
  "mcp.toolsCount": "{value} tools",
  "env.title": "Environment configuration (.env)",
  "env.open": "Environment",
  "env.search": "Search variable names",
  "env.noMatches": "No matching variables",
  "env.entriesCount": "{value} variables",
  "env.unappliedInput": "Unapplied input",
  "env.unsavedConfirm": "Discard unsaved environment changes?",
  "env.description": "Manage the .env variables the service reads; saving updates the running process immediately and applies to later runs. Sensitive values are shown masked and never returned in full.",
  "env.adminOnly": "Only administrators can view or edit the environment configuration.",
  "env.loadFailed": "Failed to load the environment configuration",
  "env.reload": "Reload",
  "env.columnKey": "Variable",
  "env.columnValue": "Value",
  "env.columnState": "State",
  "env.columnActions": "Actions",
  "env.stateSaved": "Saved",
  "env.stateEdited": "Pending",
  "env.stateNew": "New",
  "env.stateRemoved": "To remove",
  "env.emptyValue": "(empty value)",
  "env.edit": "Edit",
  "env.remove": "Remove",
  "env.restore": "Restore",
  "env.confirmEdit": "Apply",
  "env.cancelEdit": "Cancel",
  "env.newEntry": "New variable",
  "env.keyPlaceholder": "Name, e.g. FOFA_API_KEY",
  "env.valuePlaceholder": "Value",
  "env.editValuePlaceholder": "Enter the new value",
  "env.addEntry": "Add",
  "env.invalidKey": "Names must start with a letter or underscore and contain only letters, digits, or underscores",
  "env.emptyValueNotAllowed": "Value cannot be empty",
  "env.noEntries": "No environment variables yet",
  "env.discard": "Discard changes",
  "env.saveChanges": "Save changes",
  "env.changesCount": "{value} changes",
  "env.saveSuccess": "Saved to .env; applies to later runs",
  "env.sensitiveHint": "Current values of sensitive variables are never shown; entering a new value overwrites the stored one.",
  "app.initializingTitle": "Run started and initializing",
  "app.initializingDescription": "Planner is preparing the first plan, which usually takes 30–90 seconds.",
  "app.initializingHint": "The page switches automatically when the first Planner card appears and refreshes every 5 seconds. If no events appear for a long time, check the LLM service.",
  "metric.trace": "Trace",
  "metric.nodes": "Nodes",
  "metric.edges": "Edges",
  "metric.artifacts": "Artifacts",
  "graph.reasoningSubtitle": "Trace deductions among evidence, hypotheses, vulnerabilities, and exploits.",
  "graph.operationSubtitle": "Map the attack surface across hosts, services, endpoints, parameters, and credentials.",
  "graph.taskSubtitle": "View scope, goals, and tasks as a tree; milestones and blockers stay with their tasks.",
  "graph.searchPlaceholder": "Search node name, ID, or type",
  "graph.nodeType": "Node type",
  "graph.edgeType": "Relationship type",
  "graph.zoomOut": "Zoom out",
  "graph.zoomIn": "Zoom in",
  "graph.fit": "Fit canvas",
  "graph.relayout": "Run layout again",
  "graph.clearSelection": "Clear selection",
  "graph.nodeList": "Graph node list",
  "graph.nodes": "Nodes",
  "graph.noMatchingNodes": "No matching nodes",
  "graph.noVisibleNodes": "No nodes match the current filters",
  "graph.counts": "{nodes} nodes · {edges} {relations}",
  "memory.title": "Graph memory",
  "memory.subtitle": "Long-term memory distilled from public-internet collection, reusable by later Tasks",
  "memory.empty": "This run has no graph memory yet. The information-collection Agent writes here after a collection round.",
  "memory.emptyHint": "Only entities it concluded are stored; the search process itself never enters the graph.",
  "memory.total": "Memory nodes",
  "memory.confidence": "Confidence",
  "memory.sources": "Sources",
  "memory.observed": "Observed",
  "memory.inferred": "Inferred",
  "memory.unconfirmed": "Unconfirmed",
  "memory.masked": "{value} masked",
  "memory.leadsOnly": "{value} out-of-scope leads",
  "memory.leadsOnlyHint": "These nodes fall outside the authorized scope. They are kept as leads only and cannot be planned against.",
  "memory.table.entity": "Entity",
  "memory.table.type": "Type",
  "memory.table.confidence": "Confidence",
  "memory.table.provenance": "Sources",
  "memory.table.flags": "Flags",
  "memory.flagMasked": "Masked",
  "memory.flagLead": "Out-of-scope lead",
  "memory.flagImported": "Imported",
  "memory.filterType": "Entity type",
  "memory.filterConfidence": "Confidence",
  "memory.showGraph": "Graph",
  "memory.showTable": "List",
  "memory.noProvenance": "No recorded source",
  "graph.treeRelations": "tree relationships",
  "graph.relations": "relationships",
  "graph.milestones": "{value} milestones",
  "graph.blockers": "{value} blockers",
  "trace.all": "All",
  "trace.newestFirst": "Newest first",
  "trace.chronological": "Chronological",
  "trace.empty": "No trace events match the current filter",
  "trace.decision": "Decision",
  "trace.observation": "Observation",
  "trace.next": "Next",
  "trace.eventChain": "Event chain",
  "trace.noSummary": "No reasoning summary is available for this step.",
  "trace.action": "Action",
  "trace.noAction": "This step did not invoke an external tool.",
  "trace.expandDetails": "Expand execution details",
  "trace.aggregatedEvent": "View aggregated event",
  "trace.rawEvent": "View raw event",
  "trace.recordedIntent": "Agent thought",
  "trace.structuredIntent": "Reasoning basis",
  "trace.derivedIntent": "Action purpose",
  "trace.toolFailed": "Tool execution failed",
  "trace.noToolOutput": "No tool output",
  "startRun.title": "Start New Run",
  "startRun.continueTitle": "Continue from Existing Results",
  "startRun.continueAction": "Continue",
  "startRun.continueHint": "Reopens the Root Goal on this session's task graph, outcomes, credentials and artifacts and starts a new planning round; goal and scope may be adjusted.",
  "startRun.taskType": "Task type",
  "startRun.pentest": "Pentest",
  "startRun.ctf": "CTF challenge",
  "startRun.taskTypeHint": "Pentest uses Markdown scoring/report templates; CTF produces a writeup.",
  "startRun.goal": "Goal",
  "startRun.goalRequired": "Enter a goal",
  "startRun.goalPlaceholder": "Example: test the authorized target http://10.0.x.x and find all flags",
  "startRun.scope": "Authorized scope",
  "startRun.scopeRequired": "Enter the authorized scope",
  "startRun.scopePlaceholder": "Example: 10.0.0.0/24,baidu.com,*.example.com",
  "startRun.scopeFile": "Authorized scope file",
  "startRun.scopePreview": "Parsed file scope",
  "startRun.scopePreviewContent": "Parsed scope content",
  "startRun.modifyScopePreview": "Modify",
  "startRun.addScopePreview": "Add",
  "startRun.fileReadFailed": "Unable to read the authorized scope file",
  "startRun.attachments": "Task attachments",
  "startRun.attachmentsHint": "Optional. Challenge files, packet captures, vendor advisories, configs or credential exports: each file is persisted as an Artifact of this run and handed to the Executor by the Planner when a task needs it (up to 32 MiB per file, 12 files).",
  "startRun.attachmentTooLarge": "Each attachment must be at most {max}",
  "startRun.attachmentTooMany": "A run can carry at most {max} attachments",
  "startRun.maxMinutes": "Maximum runtime (minutes)",
  "startRun.parallelTasks": "Parallel tasks",
  "startRun.plannerCycles": "Maximum consecutive no-progress Planner cycles",
  "resize.navigation": "Resize navigation",
  "resize.inspector": "Resize inspector",
  "resize.title": "{label}; double-click to restore the default width",
  "connections.description": "Managed SSH/Chisel routes can reconnect in active and historical runs; sessions and raw connections are read-only.",
  "connections.empty": "No connections for this runtime",
  "connections.managed": "controllable",
  "connections.unmanaged": "read-only",
  "connections.desired": "desired",
  "connections.available": "available",
  "connections.unavailable": "unavailable",
  "connections.heartbeat": "Heartbeat",
  "connections.error": "Error",
  "connections.viewGraph": "View in status graph",
  "connections.graph": "Status graph",
  "connections.reconnect": "Reconnect",
  "connections.forget": "Forget route",
  "connections.forgetConfirm": "Permanently forget this route?",
  "status.live": "Live",
  "status.degraded": "Degraded",
  "status.stale": "Stale",
  "status.closed": "Closed",
  "status.running": "Running",
  "status.stopped": "Stopped",
  "status.completed": "Completed",
  "status.blocked": "Blocked",
  "status.pending": "Pending",
  "status.failed": "Failed",
  "inspector.currentStep": "Current Step",
  "inspector.nodeDetails": "Node Details",
  "inspector.selectTrace": "Select a trace event to inspect it",
  "inspector.summarySource": "Summary source",
  "inspector.publicOutput": "Agent public output",
  "inspector.structuredReason": "Structured rationale",
  "inspector.derivedPurpose": "System-derived purpose",
  "inspector.action": "Action",
  "inspector.noExternalAction": "No external action",
  "inspector.stage": "Stage",
  "inspector.event": "Event",
  "inspector.task": "Task",
  "inspector.time": "Time",
  "inspector.commandDetails": "Command details",
  "inspector.noArtifact": "No linked artifacts",
  "inspector.aggregatedEvent": "Aggregated event",
  "inspector.rawEvent": "Raw event",
  "inspector.loadingContent": "Loading content…",
  "inspector.loadContentFailed": "Could not load full content: {error}",
  "inspector.truncatedContent": " (content too large; showing the beginning only)",
  "inspector.selectNode": "Select a graph node to inspect its properties and relationships",
  "inspector.milestones": "Milestones {value}",
  "inspector.blockers": "Blockers {value}",
  "inspector.noMilestones": "No milestones",
  "inspector.noBlockers": "No blockers",
  "inspector.evidence": "Evidence",
  "inspector.evidenceCount": "{value} evidence items",
  "inspector.noRefs": "No linked references",
  "inspector.incoming": "Incoming {value}",
  "inspector.outgoing": "Outgoing {value}",
  "inspector.noRelations": "No relationships",
  "inspector.taskQueue": "Task Queue · {value}",
  "inspector.noTasks": "No tasks",
  "traffic.filters": "Traffic filters",
  "traffic.methodFilter": "Method filter",
  "traffic.hostFilter": "Host filter",
  "traffic.statusFilter": "Status filter",
  "traffic.taskRefFilter": "Task ref filter",
  "traffic.runRefFilter": "Run ref filter",
  "traffic.modeFilter": "Mode filter",
  "traffic.errorFilter": "Error filter",
  "traffic.onlyErrors": "Errors only",
  "traffic.noErrors": "No errors",
  "traffic.refresh": "Refresh traffic",
  "traffic.empty": "No matching traffic records",
  "traffic.pageSize": "Up to {value} per page",
  "traffic.selectExchange": "Select exchange {value}",
  "traffic.unknownHost": "unknown host",
  "traffic.requestObserved": "Request {captured} / {observed} observed",
  "traffic.responseObserved": "Response {captured} / {observed} observed",
  "traffic.capturedObserved": "{captured} captured / {observed} observed",
  "traffic.inspector": "TRAFFIC INSPECTOR",
  "traffic.exchangeDetails": "Exchange Details",
  "traffic.selectRecord": "Select a traffic record to inspect it",
  "traffic.started": "Started",
  "traffic.completed": "Completed",
  "traffic.duration": "Duration",
  "traffic.protocol": "Protocol",
  "traffic.mode": "Mode",
  "traffic.requestBytes": "Request bytes",
  "traffic.responseBytes": "Response bytes",
  "traffic.error": "Error",
  "traffic.requestHeaders": "Request Headers",
  "traffic.responseHeaders": "Response Headers",
  "traffic.requestBody": "Request Body",
  "traffic.responseBody": "Response Body",
  "traffic.headersTruncated": "Headers were truncated{reason}",
  "traffic.noHeaders": "No headers recorded",
  "traffic.displayFormat": "{side} display format",
  "traffic.loadingOnDemand": "Loading on demand…",
  "traffic.bodyReadFailed": "Body could not be read; it may be evicted or too large: {error}",
  "traffic.loadBody": "Load body (maximum 256 KiB)",
  "traffic.bodyTruncated": "Showing only the captured body portion (truncated{reason})",
  "traffic.replayAdminOnly": "Only administrators can send replays; analysts can inspect the original exchange.",
  "traffic.editReplay": "Edit and Replay",
  "traffic.replayMethod": "Replay method",
  "traffic.replayUrl": "Replay URL",
  "traffic.replayHeaderName": "Replay header name {value}",
  "traffic.replayHeaderValue": "Replay header value {value}",
  "traffic.replayBody": "Replay body",
  "traffic.deleteHeader": "Delete header {value}",
  "traffic.addHeader": "Add header",
  "traffic.editedBody": "The edited body will be sent",
  "traffic.sourceBody": "Body unchanged; sidecar will use the complete source body",
  "traffic.prepareSend": "Prepare to send",
  "traffic.confirmReplay": "Confirm Replay",
  "traffic.confirmSend": "Send Replay",
  "traffic.replayWarning": "Replay may contain sensitive headers and body data",
  "traffic.replayWarningDescription": "Confirm that you are authorized to send this request. Sensitive values are not written to URLs, localStorage, or frontend logs.",
  "traffic.headersCount": "{value} items (may include Authorization/Cookie)",
  "traffic.bodyOverride": "{value} characters ({mode} override)",
  "traffic.fullSourceBody": "Use complete source body (no override)",
  "traffic.referenceChain": "Reference Chain",
  "traffic.noReferenceChain": "No task/run/route/session/connect references",
  "traffic.bodyAvailable": "Body not loaded; click to load on demand, up to 256 KiB.",
  "traffic.bodyEvicted": "Body has been evicted from capture storage.",
  "traffic.bodyUnavailableTruncated": "Body is too large or truncated and has no readable reference{reason}.",
  "traffic.bodyNoBytes": "Body not captured: no body bytes were observed in this direction.",
  "traffic.bodyNotCaptured": "Body not captured (capture state: {state}).",
  "traffic.invalidUrl": "Invalid URL",
  "traffic.tcpReplayUnavailable": "TCP traffic can be inspected but cannot be replayed as HTTP",
  "api.csrfUnavailable": "Unable to obtain CSRF token",
  "dashboard.sessionsFailed": "Failed to load sessions: {error}",
  "dashboard.runtimeFailed": "Failed to load runtime state: {error}"
} satisfies Record<keyof typeof zh, string>;

export type TranslationKey = keyof typeof zh;
type Variables = Record<string, string | number>;

const STORAGE_KEY = "luanniao-locale";
let currentLocale: Locale = "zh-CN";

function navigatorLocale(): Locale {
  return typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("en") ? "en-US" : "zh-CN";
}

export function readStoredLocale(): Locale {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === "zh-CN" || stored === "en-US" ? stored : navigatorLocale();
  } catch {
    return navigatorLocale();
  }
}

export function getLocale(): Locale {
  return currentLocale;
}

export function translate(key: TranslationKey, variables?: Variables, locale: Locale = currentLocale): string {
  const template = locale === "en-US" ? en[key] : zh[key];
  return variables ? template.replace(/\{(\w+)\}/g, (match, name: string) => variables[name] === undefined ? match : String(variables[name])) : template;
}

export function formatDateTime(value?: string | number | Date, locale: Locale = currentLocale): string {
  if (value === undefined) return "-";
  const date = value instanceof Date ? value : new Date(value);
  return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "medium", hour12: false }).format(date) : "-";
}

export function formatRelativeTime(value?: string | number | Date, locale: Locale = currentLocale, now = Date.now()): string {
  if (value === undefined) return "-";
  const time = (value instanceof Date ? value : new Date(value)).getTime();
  if (!Number.isFinite(time)) return "-";
  const diff = now - time;
  if (diff < 60_000) return translate("common.justNow", undefined, locale);
  if (diff < 3_600_000) return translate("common.minutesAgo", { value: Math.floor(diff / 60_000) }, locale);
  if (diff < 86_400_000) return translate("common.hoursAgo", { value: Math.floor(diff / 3_600_000) }, locale);
  return translate("common.daysAgo", { value: Math.floor(diff / 86_400_000) }, locale);
}

export function formatNumber(value: number, locale: Locale = currentLocale, options?: Intl.NumberFormatOptions): string {
  return new Intl.NumberFormat(locale, options).format(value);
}

export function formatBytes(value: number, locale: Locale = currentLocale): string {
  if (value >= 1024 * 1024) return `${formatNumber(value / (1024 * 1024), locale, { maximumFractionDigits: 1 })} MB`;
  if (value >= 1024) return `${formatNumber(value / 1024, locale, { maximumFractionDigits: 1 })} KB`;
  return `${formatNumber(value, locale)} B`;
}

export function formatDuration(value: number, locale: Locale = currentLocale): string {
  return value >= 1000 ? `${formatNumber(value / 1000, locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} s` : `${formatNumber(value, locale)} ms`;
}

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: TranslationKey, variables?: Variables) => string;
  formatDate: (value?: string | number | Date) => string;
  formatRelative: (value?: string | number | Date) => string;
  formatNumber: (value: number, options?: Intl.NumberFormatOptions) => string;
  formatBytes: (value: number) => string;
  formatDuration: (value: number) => string;
}

const defaultContext: LanguageContextValue = {
  locale: "zh-CN",
  setLocale: () => undefined,
  toggleLocale: () => undefined,
  t: (key, variables) => translate(key, variables, "zh-CN"),
  formatDate: (value) => formatDateTime(value, "zh-CN"),
  formatRelative: (value) => formatRelativeTime(value, "zh-CN"),
  formatNumber: (value, options) => formatNumber(value, "zh-CN", options),
  formatBytes: (value) => formatBytes(value, "zh-CN"),
  formatDuration: (value) => formatDuration(value, "zh-CN")
};

const LanguageContext = createContext<LanguageContextValue>(defaultContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(readStoredLocale);

  const setLocale = useCallback((next: Locale) => {
    currentLocale = next;
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // Keep language switching available when browser storage is blocked.
    }
    setLocaleState(next);
  }, []);
  const toggleLocale = useCallback(() => setLocale(locale === "zh-CN" ? "en-US" : "zh-CN"), [locale, setLocale]);

  useEffect(() => {
    currentLocale = locale;
    document.documentElement.lang = locale;
    document.title = translate("app.title", undefined, locale);
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    toggleLocale,
    t: (key, variables) => translate(key, variables, locale),
    formatDate: (input) => formatDateTime(input, locale),
    formatRelative: (input) => formatRelativeTime(input, locale),
    formatNumber: (input, options) => formatNumber(input, locale, options),
    formatBytes: (input) => formatBytes(input, locale),
    formatDuration: (input) => formatDuration(input, locale)
  }), [locale, setLocale, toggleLocale]);

  return <LanguageContext.Provider value={value}><ConfigProvider locale={locale === "zh-CN" ? zhCN : enUS}>{children}</ConfigProvider></LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}
